/**
 * Prefijo para identificar IMEIs generados automáticamente
 */
const AUTO_IMEI_PREFIX = "AUTO-";

/**
 * Genera un UUID usando la API crypto disponible en Node.js y navegadores
 * @returns UUID string
 */
function generateUUID(): string {
  // Usa crypto.randomUUID() que está disponible en Node.js 19+ y navegadores modernos
  if (typeof crypto !== "undefined" && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  // Fallback para entornos más antiguos
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Genera un IMEI automático con formato: AUTO-{uuid}
 * @returns IMEI generado automáticamente
 */
export function generateAutoImei(): string {
  return `${AUTO_IMEI_PREFIX}${generateUUID()}`;
}

/**
 * Verifica si un IMEI fue generado automáticamente
 * @param imei - IMEI a verificar
 * @returns true si el IMEI fue generado automáticamente
 */
export function isAutoGeneratedImei(imei: string | null | undefined): boolean {
  if (!imei) return false;
  return imei.startsWith(AUTO_IMEI_PREFIX);
}

/**
 * Formatea un IMEI para mostrar en la UI
 * - Si es null/undefined: retorna "-"
 * - Si es generado automáticamente: retorna "N/A" o los últimos 8 caracteres
 * - Si es un IMEI real: retorna el IMEI completo
 * @param imei - IMEI a formatear
 * @param showAutoImei - Si true, muestra los últimos 8 caracteres del UUID generado. Si false, muestra "N/A"
 * @returns IMEI formateado para mostrar
 */
export function formatImeiForDisplay(
  imei: string | null | undefined,
  showAutoImei: boolean = false,
): string {
  if (!imei) return "-";

  if (isAutoGeneratedImei(imei)) {
    if (showAutoImei) {
      // Mostrar últimos 8 caracteres del UUID (sin el prefijo AUTO-)
      const uuidPart = imei.replace(AUTO_IMEI_PREFIX, "");
      return `AUTO-${uuidPart.slice(-8).toUpperCase()}`;
    }
    return "N/A";
  }

  return imei;
}

/**
 * Genera un IMEI automático si no se proporciona uno
 * @param imei - IMEI proporcionado (puede ser null, undefined o string vacío)
 * @returns IMEI proporcionado o uno generado automáticamente
 */
export function generateImeiIfNeeded(imei: string | null | undefined): string {
  if (!imei || imei.trim().length === 0) {
    return generateAutoImei();
  }
  return imei.trim();
}
